source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwipeViewController_Example', :exclusive => true do
  pod 'SwipeViewController', :path => '../'
end

target 'SwipeViewController_Tests', :exclusive => true do
  pod 'SwipeViewController', :path => '../'

  
end
