source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'SwipeViewController_Example' do
  pod 'SwipeViewController', :path => '../'
end

target 'SwipeViewController_ExampleTests' do
  pod 'SwipeViewController', :path => '../'

  
end
